---
title: "household_data"
output: html_document
date: "2026-04-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Packages

```{r}
# Load the package.
library(datasets)
library(tidyr)
library(stringr)
library(dplyr)
library(rvest)
library(stringr)
library(lubridate)
library(tidytext)
library(ggplot2)
library(knitr)
library(kableExtra)
```

## Data Cleaning

### Census

```{r}
census <- read.csv('data/census/census_96_21.csv')

census$QRTYP |> unique()

census |>
  mutate(
    period = year |> factor(levels=year|>unique()),
    LQTYPEDesc = ifelse(QRTYP==9, 4, QRTYP) |> 
      factor(levels=0:4,labels=c('All housing','Public housing','Subsidised housing','Private housing','Others'))
  ) |>
  group_by(period,HHNO) |>
  summarise(
    inc_grp = first(DJHHINC),
    LQTYPEDesc = first(LQTYPEDesc)
  ) |>
  group_by(period,LQTYPEDesc) |>
  summarise(
    inc_grp = median(inc_grp)
  ) |>
  arrange(period,LQTYPEDesc)
```

### GDP

```{r}
gdp <- read.csv('data/household/gdp_pce.csv')
gdp <- gdp |>
  pivot_wider(period,names_from=GDP_COMPONENTDesc,values_from = figure)
colnames(gdp) <- c('period','gdp_y','pce')
head(gdp)
```

### Consumption

```{r}
cons <- read.csv('data/household/household_expenditure.csv')
cons$GROUPDesc <- cons$GROUPDesc |> 
  factor(levels=
           c('Alcoholic drinks and tobacco','Electricity, gas and water','Clothing and footwear','Miscellaneous goods','Durable goods','Transport','Miscellaneous services','Food','Housing')
         )
cons$LQTYPEDesc <- ifelse(cons$LQTYPEDesc == 'Total', 'All housing', cons$LQTYPEDesc) |>
  factor(levels=c('All housing','Public housing','Subsidised housing','Private housing'))
#cons$period <- cons$period |> factor(labels=cons$period |> unique())
cons <- cons |> select(period,GROUPDesc,LQTYPEDesc,figure)

cons |> head()
```

### Consumer prices

```{r}
cpi <- read.csv('data/household/consumer_price.csv')
cpi$GROUPDesc <- ifelse(cpi$GROUPDesc == 'Total','All goods',cpi$GROUPDesc)
cpi$GROUPDesc <- cpi$GROUPDesc |> 
  factor(levels=
           c('All goods','Alcoholic drinks and tobacco','Electricity, gas and water','Clothing and footwear','Miscellaneous goods','Durable goods','Transport','Miscellaneous services','Food','Housing')
         )
#cpi$period <- cpi$period |> factor(labels=cpi$period |> unique())
cpi$sv <- cpi$sv |> 
  factor(
    levels=c('CC_CM_1920','A_CM_1920','B_CM_1920','C_CM_1920'),
    labels=c('cpi','cpi_a','cpi_b','cpi_c')
  )
cpi <- cpi |> pivot_wider(names_from = sv, values_from = figure)
cpi <- cpi |> select(period,GROUPDesc,cpi,cpi_a,cpi_b,cpi_c)
cpi <- cpi |>
  arrange(period,GROUPDesc) |>
  group_by(GROUPDesc) |>
  mutate(
    cpi = cpi / first(cpi) * 100,
    cpi_a = cpi_a / first(cpi_a) * 100,
    cpi_b = cpi_b / first(cpi_b) * 100,
    cpi_c = cpi_c / first(cpi_c) * 100
  )

head(cpi)
```

### Household dist

```{r}
dist <- read.csv('data/household/household_types.csv')
dist$LQTYPEDesc <- dist$LQTYPEDesc |>
  factor(
    levels=c('Total','Public rental housing','Subsidised home ownership housing','Private permanent housing','Temporary housing'),
    labels=c('All housing','Public housing','Subsidised housing','Private housing','Temporary housing')
    )
#dist$period <- dist$period |> factor(labels=dist$period |> unique())
dist <- dist |> select(period,LQTYPEDesc,svDesc,figure)
colnames(dist) <- c('period','LQTYPEDesc','svDesc','number')

head(dist)
```

### Household size

```{r}
size <- read.csv('data/household/household_sizes.csv')
size$LQTYPEDesc <- size$LQTYPEDesc |>
  factor(
    levels=c('Total','Public rental housing','Subsidised home ownership housing','Private permanent housing','Temporary housing'),
    labels=c('All housing','Public housing','Subsidised housing','Private housing','Temporary housing')
    )
#size$period <- size$period |> factor(labels=size$period |> unique())
size <- size |> select(period,LQTYPEDesc,figure)
colnames(size) <- c('period','LQTYPEDesc','person')

head(size)
```

### Household income

```{r}
income <- read.csv('data/household/household_income.csv')
income$LQTYPEDesc <- income$LQTYPEDesc |>
  factor(
    levels=c('Total','Public rental housing','Subsidised home ownership housing','Private permanent housing','Temporary housing'),
    labels=c('All housing','Public housing','Subsidised housing','Private housing','Temporary housing')
    )
#income$period <- income$period |> factor(labels=income$period |> unique())
income$sv <- income$sv |> 
  factor(
    levels=c('MED_DH_INC','MED_DH_INC_XEI'),
    labels=c('inc','inc_eco')
  )
income <- income |> pivot_wider(names_from = sv, values_from = figure)
income <- income |> select(period,LQTYPEDesc,inc,inc_eco)

head(income)
```

## Aggregate

```{r}
gdp |>
  filter(period <= 2019)# |>
  mutate(share=pce/gdp_y*100) |>
  ggplot(aes(x=period)) +
  geom_line(aes(y=share),color='black',linewidth=1) +
  geom_point(aes(y=share),color='black',shape=4,size=3,stroke=1) +
  labs(
    title = "Private consumption expenditure as share of GDP",
    subtitle = "%, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "%"
  ) +
  theme_classic()
```

## All households

### Absolute changes

```{r}
cons |>
  filter(LQTYPEDesc == 'All housing') |>
  arrange(GROUPDesc,period) |>
  ggplot() +
  geom_bar(aes(x=period,y=figure,fill=GROUPDesc),color='white',stat='identity') +
  labs(
    title = "Monthly household expenditure",
    subtitle = "HK$, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "HKD",
    fill = 'Commodity'
  ) +
  theme_classic()

cons |>
  filter(LQTYPEDesc == 'All housing') |>
  group_by(period) |>
  mutate(tot=sum(figure)) |>
  arrange(GROUPDesc,period) |>
  group_by(GROUPDesc) |>
  summarise(
    pct_change = last(figure) / first(figure) * 100 - 100,
    tot_pct_change = last(tot) / first(tot) * 100 - 100
    ) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,pct_change),y=pct_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE) +
  geom_hline(aes(yintercept = mean(tot_pct_change)), 
             linetype = 'dashed', color = 'black', linewidth = 1) +
  coord_flip() +
  labs(
    title = "Monthly household expenditure",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc == 'All housing') |>
  group_by(period,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(period,GROUPDesc) |>
  pivot_wider(names_from = period,values_from = HKD) |>
  kable(
    caption = "Monthly household expenditure",
    digits = 2
  )
```

### Changes in shares

```{r}
cons |>
  filter(LQTYPEDesc == 'All housing') |>
  group_by(period,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(GROUPDesc,period) |>
  ggplot() +
  geom_bar(aes(x=as.numeric(as.character(period)),y=share,fill=GROUPDesc),color='white',stat='identity',position='stack') +
  labs(
    title = "Share of monthly household expenditure",
    subtitle = "%, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "%",
    fill = 'Commodity'
  ) +
  theme_classic()

cons |>
  filter(LQTYPEDesc == 'All housing') |>
  group_by(period,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(GROUPDesc,period) |>
  group_by(GROUPDesc) |>
  summarise(share_change = last(share) - first(share)) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,share_change),y=share_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE) +
  coord_flip() +
  labs(
    title = "Share of monthly household expenditure",
    subtitle = "Change in %, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc == 'All housing') |>
  group_by(period,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(period,GROUPDesc) |>
  pivot_wider(-HKD,names_from = period,values_from = share) |>
  kable(
    caption = "Share of monthly household expenditure",
    digits = 2
  )
```

### Nominal vs real

```{r}
cons_cpi <- cons |> 
  filter(LQTYPEDesc == 'All housing')
cons_cpi <- cons_cpi |>
  rbind(
    cons_cpi |> group_by(period) |> summarise(
      GROUPDesc='All goods',
      LQTYPEDesc='All housing',
      figure=sum(figure)
    )
  ) |> 
  arrange(period,GROUPDesc,LQTYPEDesc)
cons_cpi <- cpi |>
  merge(
    cons_cpi,
    by=c('period','GROUPDesc'),all.y=TRUE
    ) |> 
  arrange(period,LQTYPEDesc)
```

```{r}
cons_cpi |>
  filter(GROUPDesc == 'All goods') |>
  ggplot(aes(x = as.numeric(as.character(period)))) +
  # Plot consumption normally
  geom_bar(aes(y = figure,fill=GROUPDesc), color='white', stat='identity') +
  # Plot CPI but multiply it to match consumption's scale
  geom_line(aes(y = cpi * 310),linewidth=1,linetype='dashed') +
  geom_point(aes(y = cpi * 310),shape=4,size=3,stroke=1) +
  # Add the secondary axis
  scale_y_continuous(
    name = "HK$",
    sec.axis = sec_axis(~./310, name = "CPI")
  ) +
  labs(
    title = "Nominal expenditure (LHS) vs consumer price (RHS)",
    subtitle = "Bars as HK$, line as CPI (1999=100), (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    fill = 'Commodity'
  ) +
  theme_classic()

cons_cpi |>
  filter(GROUPDesc != 'All goods') |>
  mutate(real = figure / cpi * 100) |>
  ggplot(aes(x = as.numeric(as.character(period)))) +
  # Plot consumption normally
  geom_bar(aes(y = real,fill=GROUPDesc), color='white', stat='identity',position='stack') +
  labs(
    title = "Real household expenditure",
    subtitle = "HK$ in 1999, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = 'HK$ in 1999',
    fill = 'Commodity'
  ) +
  theme_classic()

cons_cpi |>
  filter(GROUPDesc != 'All goods') |>
  mutate(real = figure / cpi * 100) |>
  arrange(GROUPDesc,period) |>
  group_by(GROUPDesc) |>
  summarise(pct_change = last(real) / first(real) * 100 - 100) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,pct_change),y=pct_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE) +
  coord_flip() +
  labs(
    title = "Real household expenditure",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons_cpi |>
  filter(GROUPDesc != 'All goods') |>
  arrange(GROUPDesc,period) |>
  ggplot(aes(x=as.numeric(as.character(period)))) +
  geom_line(aes(y = cpi,color=GROUPDesc),linewidth=1) +
  geom_point(aes(y = cpi,color=GROUPDesc),shape=4,size=3,stroke=1) +
  labs(
    title = "Consumer price level",
    subtitle = "CPI (1999=100), (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "CPI",
    color = 'Commodity'
  ) +
  theme_classic()

cons_cpi |>
  filter(GROUPDesc != 'All goods') |>
  arrange(GROUPDesc,period) |>
  group_by(GROUPDesc) |>
  summarise(pct_change = last(cpi) / first(cpi) * 100 - 100) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,pct_change),y=pct_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE) +
  coord_flip() +
  labs(
    title = "Consumer price level",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "%",
    color = 'Commodity'
  ) +
  theme_classic()
  

cons_cpi |>
  filter(GROUPDesc != 'All goods') |>
  mutate(real = figure / cpi * 100) |>
  arrange(period,GROUPDesc) |>
  pivot_wider(GROUPDesc,names_from = period,values_from = real) |>
  kable(
    caption = "Real household expenditure",
    digits = 2
  )
```

## By housing type

```{r}
inc_sampled <- income |>
  filter(period %in% cons$period)

cons |> merge(inc_sampled, by=c('period','LQTYPEDesc'))
```

### Income

```{r}
inc_sampled |>
  filter(LQTYPEDesc != 'All housing') |>
  arrange(LQTYPEDesc,period) |>
  ggplot() +
  geom_bar(aes(x=period,y=inc,fill=LQTYPEDesc),color='white',stat='identity',position='dodge') +
  labs(
    title = "Monthly household income, by housing type",
    subtitle = "HK$, (2004 - 2019)",
    caption = "Data from CSD HK",
    x = "Housing type",
    y = "HKD",
    fill = 'Housing type'
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)
  )

inc_sampled |>
  filter(LQTYPEDesc != 'All housing') |>
  arrange(LQTYPEDesc,period) |>
  group_by(LQTYPEDesc) |>
  summarise(pct_change = last(inc_eco) / first(inc_eco) * 100 - 100) |>
  ggplot() +
  geom_bar(aes(x=LQTYPEDesc,y=pct_change,fill=LQTYPEDesc),color='white',stat='identity',show.legend=FALSE) +
  coord_flip() +
  labs(
    title = "Monthly household income, by housing type",
    subtitle = "% change, (2004 - 2019)",
    caption = "Data from CSD HK",
    x = "Housing type",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

inc_sampled |>
  filter(LQTYPEDesc != 'All housing') |>
  arrange(LQTYPEDesc,period) |>
  pivot_wider(LQTYPEDesc,names_from = period,values_from = inc_eco) |>
  kable(
    caption = "Monthly household income, by housing type",
    digits = 2
  )
```

### Saving

```{r}

```

### Expenditure

```{r}
cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc) |>
  summarise(HKD=sum(figure)) |>
  ggplot() +
  geom_bar(aes(x=period,y=HKD,fill=LQTYPEDesc),color='white',stat='identity',position='dodge') +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "HK$, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Housing type",
    y = "HKD",
    fill = 'Housing type'
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(LQTYPEDesc,period) |>
  group_by(LQTYPEDesc) |>
  summarise(pct_change = last(HKD) / first(HKD) * 100 - 100) |>
  ggplot() +
  geom_bar(aes(x=LQTYPEDesc,y=pct_change,fill=LQTYPEDesc),color='white',stat='identity',show.legend=FALSE) +
  coord_flip() +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Housing type",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(period,LQTYPEDesc) |>
  pivot_wider(names_from = period,values_from = HKD) |>
  kable(
    caption = "Monthly household expenditure, by housing type",
    digits = 2
  )
```

### Absoluate change

```{r}
cons |> 
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(GROUPDesc,period) |>
  ggplot() +
  geom_bar(aes(x=period,y=HKD,fill=GROUPDesc),color='white',stat='identity',position='stack') +
  facet_wrap(~LQTYPEDesc, nrow = 1) +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "HK$, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "HKD",
    fill = 'Commodity'
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  group_by(LQTYPEDesc,GROUPDesc) |>
  summarise(pct_change = last(HKD) / first(HKD) * 100 - 100) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,pct_change),y=pct_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE,position='dodge') +
  coord_flip() +
  facet_wrap(~LQTYPEDesc, nrow = 1) +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  pivot_wider(names_from = period,values_from = HKD) |>
  kable(
    caption = "Monthly household expenditure, by housing type",
    digits = 2
  )
```

### Changes in share

```{r}
cons |> 
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period,LQTYPEDesc) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(GROUPDesc,period) |>
  ggplot() +
  geom_bar(aes(x=period,y=share,fill=GROUPDesc),color='white',stat='identity',position='stack') +
  facet_wrap(~LQTYPEDesc, nrow = 1) +
  labs(
    title = "Share of monthly household expenditure, by housing type",
    subtitle = "%, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "%",
    fill = 'Commodity'
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period,LQTYPEDesc) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  group_by(LQTYPEDesc,GROUPDesc) |>
  summarise(share_change = last(share) - first(share)) |>
  ggplot() +
  geom_bar(aes(x=reorder(GROUPDesc,share_change),y=share_change,fill=GROUPDesc),color='white',stat='identity',show.legend=FALSE,position='dodge') +
  coord_flip() +
  facet_wrap(~LQTYPEDesc, nrow = 1) +
  labs(
    title = "Share of monthly household expenditure, by housing type",
    subtitle = "change in %, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  group_by(period,LQTYPEDesc) |>
  mutate(share = HKD/sum(HKD)*100) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  pivot_wider(-HKD,names_from = period,values_from = share) |>
  kable(
    caption = "Share of monthly household expenditure, by housing type",
    digits = 2
  )
```

### By commodity

```{r}
cons |> 
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(GROUPDesc,period) |>
  filter(GROUPDesc %in% c('Housing','Food','Transport','Miscellaneous goods')) |>
  ggplot() +
  geom_bar(aes(x=period,y=HKD,fill=LQTYPEDesc),color='white',stat='identity',position='dodge') +
  facet_wrap(~GROUPDesc, nrow = 2) +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "HK$, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Year",
    y = "HKD",
    fill = 'Commodity'
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(angle = 30, vjust = 1, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  group_by(LQTYPEDesc,GROUPDesc) |>
  summarise(pct_change = last(HKD) / first(HKD) * 100 - 100) |>
  filter(GROUPDesc %in% c('Housing','Food','Transport','Miscellaneous goods')) |>
  ggplot() +
  geom_bar(aes(x=LQTYPEDesc,y=pct_change,fill=LQTYPEDesc),color='white',stat='identity',show.legend=FALSE,position='dodge') +
  coord_flip() +
  facet_wrap(~GROUPDesc, nrow = 2) +
  labs(
    title = "Monthly household expenditure, by housing type",
    subtitle = "% change, (1999 - 2019)",
    caption = "Data from CSD HK",
    x = "Commodity",
    y = "%",
  ) +
  theme_classic() +
  theme(
    axis.text.y = element_text(angle = 30, vjust = 0, hjust = 1)
  )

cons |>
  filter(LQTYPEDesc != 'All housing') |>
  group_by(period,LQTYPEDesc,GROUPDesc) |>
  summarise(HKD=sum(figure)) |>
  filter(GROUPDesc %in% c('Housing','Food','Transport','Miscellaneous goods')) |>
  arrange(LQTYPEDesc,GROUPDesc,period) |>
  pivot_wider(names_from = period,values_from = HKD) |>
  kable(
    caption = "Monthly household expenditure, by housing type",
    digits = 2
  )
```
